### PR TITLE
V2.47.0

### PR DESCRIPTION
**Pull request by VitorEAFeliciano**
vectorcall_decoration double definition, missing vectorcall fix for not mangling all proc's and proto's, and merge conflits.

### CODE REVIEW

**Comment by john-terraspace** [comment]
After this update, there were 11 merge conflicts in codegen.c.. after fixing this and pulling, the build failed due to missing braces in mangle.c .. fixed that.. built, still over 15 failing regression tests.
I'm going to revert the whole 2.47 version back to a stable build, I can't accept these changes in as they're just not working properly.

**Comment by VitorEAFeliciano** [comment]
Sorry, the merges are messing with the code, after sync both repos fixed and tested the regressions, some regressions not passing for this files for avx512 wrong instruction operands, and the test for errors, and miss .inc files, I have not configures yet.

Going to finish some code and send You a complete build with source and the regressions tests objects and errors.

Sorry for all the trouble with the code, github not supposed to do so bad merges.

I'm doing the trick to get clean files with

git reset eb6477d06e3d9ce32c7887479508a61092de91f5

git reset --soft HEAD@{1}
git commit -m "Revert to eb6477d06e3d9ce32c7887479508a61092de91f5"
delete all files and not the .git
git reset --hard

I send You new message with 7z file with the code and builds.

**Comment by john-terraspace** [comment]
I’m always happy for help on the project!

Perhaps the best way to approach this is lets do the following:

 

I will make a new branch 2.47.1 which has my latest version, it has a bunch of fixes from Habran and myself and all regressions are good.

 

For the changes you’re looking at, lets break it down into separate items and do them one at a time so we can test as we go?

IE: 

1.	Add the __m512 types

..

 

I’m not sure what else you were looking at changing ? Lets discuss these changes and we can see what needs to happen.

**Comment by VitorEAFeliciano** [comment]
Ok, I break down the additions by steps, its only 3, for the,

1.  __m512 data types.

2. The mangle for vectorcall, only has option at command-line, to only apply at selected proto proc VECTORCALL <>

3. GCC and CLANG UASM build on linux fixes.

Index Header File for the changes, trying to explain the steps changes in the code, the file is best view with notepad+ or something similar.

[vitor-changes.zip](https://github.com/Terraspace/UASM/files/2190054/vitor-changes.zip)

**Comment by john-terraspace** [comment]
Ok excellent, let me go through them and see.

I’m surprised you needed to make fixes for linux/osx builds, I build on both with gcc/clang all the time. What problem were you encountering there? *Perhaps I should double check the make files I use are actually in the repository*

**Pull request merged**
